---
resources:
  - allow-argocd.yaml
  - https://github.com/openshift-pipelines/pipelines-as-code/releases/download/v0.14.2/release.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: "build"


patchesJson6902:
  - target:
      kind: Namespace
      name: pipelines-as-code
    patch: |-
      - op: add
        path: "/metadata/labels"
        value:
          argocd.argoproj.io/managed-by: openshift-gitops
