resources:
  - https://github.com/openshift-pipelines/pipelines-as-code/releases/download/v0.12.0/release.k8s.yaml
  - webhook-ingress.yaml
  - controller-ingress.yaml
patches:
  - target:
      kind: Deployment
      name: pipelines-as-code-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/ports/0/protocol
        description: Protocol field is required
        value: TCP
  - target:
      kind: Deployment
      name: pipelines-as-code-watcher
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/ports/0/protocol
        description: Protocol field is required
        value: TCP
  - target:
      kind: Deployment
      name: pipelines-as-code-webhook
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/ports/0/protocol
        description: Protocol field is required
        value: TCP
  - target:
      kind: Service
      name: pipelines-as-code-webhook
    patch: |-
      - op: add
        path: /spec/ports/0/protocol
        description: Protocol field is required
        value: TCP
