---
apiVersion: v1
kind: Secret
metadata:
  name: minio-storage-configuration
  namespace: tekton-results
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="$TEKTON_RESULTS_MINIO_USER"
    export MINIO_ROOT_PASSWORD="$TEKTON_RESULTS_MINIO_PASSWORD"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
