---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-results-api
  namespace: tekton-results
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            # Enable logs api
            - name: LOGS_API
              value: "true"
            # Set up log type "S3"
            - name: LOGS_TYPE
              value: S3
            # Set up S3 bucket name, where will be stored logs
            - name: S3_BUCKET_NAME
              value: tekton-results
            # Set up Minio tenant endpoint url
            - name: S3_ENDPOINT
              value: https://minio.tekton-results.svc.cluster.local
            # Set up S3 endpoint host name without bucket prefix
            - name: S3_HOSTNAME_IMMUTABLE
              value: "true"
            # Set up S3 region
            - name: S3_REGION
              value: us-east-1
      initContainers:
        - name: mc
          image: >-
            docker.io/minio/mc:RELEASE.2023-01-28T20-29-38Z
          command:
            - /bin/bash
          args:
            - '-c'
            - |
              mc --config-dir /tmp config host add minio "$S3_ENDPOINT" "$S3_ACCESS_KEY_ID" "$S3_SECRET_ACCESS_KEY";
              if [ -z "$(mc --config-dir /tmp ls minio | grep tekton-results)" ]; then
                mc --config-dir /tmp mb --with-lock --region "$S3_REGION" minio/"$S3_BUCKET_NAME";
                echo "Minio bucket $S3_BUCKET_NAME successfully created.";
              fi
          imagePullPolicy: Always
          volumeMounts:
            - name: ca-s3
              mountPath: /etc/ssl/certs/s3-cert.crt
              subPath: s3-cert.crt
          env:
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: S3_ACCESS_KEY_ID
                  name: tekton-results-s3
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: S3_SECRET_ACCESS_KEY
                  name: tekton-results-s3
            - name: S3_BUCKET_NAME
              value: tekton-results
            - name: S3_ENDPOINT
              value: https://minio.tekton-results.svc.cluster.local
            - name: S3_REGION
              value: us-east-1
